### SET PACKAGE CONFIGURATION PARAMETERS HERE #################################

top = '..'
out = top + '/build'

int_deps = []
ext_deps = ['BOOST.SPIRIT', 'BOOST.TEST', 'BOOST.LOG', 'EIGEN']

###############################################################################

execfile('waf-extras/common-package.py')
