### SET TASK CONFIGURATION PARAMETERS HERE ####################################

# Set the top dir and the build dir
top = '../..'
out = top + '/build'

task_name = 'nlpgo_sentencebreaker'
int_deps  = ['nlpgo/algo', 'nlpgo/attr', 'nlpgo/core', 'nlpgo/util']
ext_deps  = ['CLD2', 'MITIE']

###############################################################################

execfile('waf-extras/common-task.py')
